name: account_config_plugin
description: "Account config plugin"
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  provider: ^6.1.5+1
  encrypt: ^5.0.3
  crypto: ^3.0.7
  intl: ^0.20.02

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  